### ISSUE TITLE
Running FXForm on Android

### ISSUE THREAD

**Issue by omdaCh** [dooApp/FXForm2#113]
I tried to run FXForm on Android but it seems that there is some probleme with hibernate-validator.

**Comment by amischler** [comment]
Nice to see that there are some experiments with Android! We did not try it yet. Which solution did you use? JavaFXPorts?
Can you provide more informations about the errors you get? (error message, stacktrace, android version,...).

**Comment by omdaCh** [comment]
I used JavaFXPorts and gluon plugin on netbeans. The apk is build without probleme.
but the probleme is when running it on android device , I get an hibernate probleme. after removing the validation process from fxform the apk has worked normal, after I will of search I found that there is some probleme of hibernate in android.

**Comment by amischler** [comment]
Hi! Did you find more information about the hibernate issue? Is there anything to fix in FXForm2 regarding this ticket?

**Comment by omdaCh** [comment]
Hi michael, I found some solutions on the web but I can't test them because
I haven't an android phone and my income doesn't allow me to buy one. if I
could I will help to solve this issue.

2015-11-03 8:58 GMT+01:00 Antoine Mischler <notifications@github.com>:

**Comment by amischler** [comment]
Hi,
Do you have more details about the issue with the hibernate validator issue when running on Android ?
Is there any modification required in FXForm2 ?

**Comment by amischler** [comment]
No update on this, I'm closing the issue.
