### ISSUE TITLE
Demo example of CRUD using FXForm2

### ISSUE THREAD

**Issue by amitjain3** [dooApp/FXForm2#117]
Hi

Could you provide basic example of CRUD using FXForm2 using JPA.

One more thing if we generate form dynamically , can we generate the action button also dynamically for eg. save , cancel, clear

**Comment by amitjain3** [comment]
Hi,

I am able to implement the CRUD functionality using FXform2 , JPA , Hibernate.

**Comment by amischler** [comment]
Sorry for the late answer and glad to see that you manage to get your implementation working. Feel free to share your demo, this might be interesting for other users.

Adding save, cancel and clear actions might require better control over the bindings between model and view, this is linked to this improvement request : https://github.com/dooApp/FXForm2/issues/104
