### ISSUE TITLE
Jigsaw NoClassDefFoundError: javafx/scene/layout/GridPaneBuilder

### ISSUE THREAD

**Issue by rahmanusta** [dooApp/FXForm2#128]
Hello, I try to use FXForm2 in Java 9 build 9-ea+152. It gives "NoClassDefFoundError: javafx/scene/layout/GridPaneBuilder" error.

**Comment by rahmanusta** [comment]
Here is the pull request https://github.com/dooApp/FXForm2/pull/129

**Comment by amischler** [comment]
Deployed in 8.0.19-SNAPSHOT

**Comment by amischler** [comment]
Great that you tried FXForm2 with Java 9. Did you experience any other issue ? If not, i will release FXForm2 including this fix to be Java 9 compatible.

**Comment by amischler** [comment]
Deployed in 8.1.0
