### ISSUE TITLE
Allow to set custom ResourceProvider

### ISSUE THREAD

**Issue by xylo** [dooApp/FXForm2#138]
The "resourceProvider" is the last *Provider property of FXForm which hasn't yet been implemented as JavaFX property.  Instead, it's a final field and cannot be replaced.  I think it would be nice if users could replace this provider as well, because not everybody wants to store the field name translations in a resource bundle.  E.g. in my case the translations are already stored in a database with thousands of other translations, thus, building a big resource bundle with all those translations doesn't make much sense in my case.  Instead I would like to be able to redirect the access to the translations to my database.

**Comment by amischler** [comment]
Thanks. Deployed in 8.1.1-SNAPSHOT.

**Comment by Rizen59** [comment]
Deployed in 8.1.1

**Comment by xylo** [comment]
Thanks for the new release.
