### ISSUE TITLE
How to add a custom validator if a certain annotation is present

### ISSUE THREAD

**Issue by xylo** [dooApp/FXForm2#140]
When I annotate a `String` property with `@Size(min=2, max=10)` FXForm automatically adds the corresponding validator to the field.

Is it possible to add custom annotation-validator mappings?  For instance I would like to support the @Before annotation and some others.

**Comment by xylo** [comment]
After creating this issue I saw that questions should be posted on stackoverflow.  So I posted this one here: http://stackoverflow.com/questions/43489884/how-to-add-a-custom-validator-if-a-certain-annotation-is-present

BTW: I added the tag fxform2, in case you want to subscribe to it.

**Comment by amischler** [comment]
Answered on SO. Thanks for adding the tag.
