### ISSUE TITLE
Add custom factory provided for UUID class

### ISSUE THREAD

**Issue by ouaibsky** [dooApp/FXForm2#147]
Hi
I got a mini with UUID attribute and would like to be able to change an UUID value in fxform2.
I add a custom default factory provided with a TextFieldFactory for a WrapperTypeHandler(UUID).
I have to error and a text field is displayed but empty (with no UUID set into the mojo)

Do I missed something to configure ?

Thx
Christophe

**Comment by amischler** [comment]
If your property if of type UUID and your view is exposing a StringProperty (which is the case for the default TextFieldFactory), then you should register an Adapter that will be responsible for converting the value between the UUID and the String. (see https://github.com/dooApp/FXForm2/wiki/Advanced-customization#adapters-customizing-bindings-in-fxform2)

Can you see any related messages in your logs ?

**Comment by amischler** [comment]
No update on this, I'm closing the issue.
