### ISSUE TITLE
Handling dynamic source objects

### ISSUE THREAD

**Issue by usander** [dooApp/FXForm2#30]
I'm dealing with a bean which has a map property like

``` java
Map<String, String> userMap
```

Showing this map with FXForm2 using an adaptor and a factory is not a problem, but the user should be able to add or remove entries to or from the map such that I need to update the form after each operation. I can do this partial re-generation of the form by

1) using a lot of code in the factory class or by 
2) re-generating the entire form, by which I would probably lose any input values that were not stored in the data model (because they were invalid, for instance).

Is there a recommended way for doing this? Or is this maybe a use case that FXForm2 does not want to address?

Cheers,
Uwe

**Comment by amischler** [comment]
https://github.com/dooApp/FXForm2/issues/99
