### ISSUE TITLE
The PropertyElementFactory should return a ReadOnlyPropertyMethodElement if the property method returns a ReadOnlyProperty.

### ISSUE THREAD

**Issue by Rizen59** [dooApp/FXForm2#95]
Currently the PropertyElementFactory checks the field type and not the method type.

Reproduction :
- Create a bean with a DoubleProperty
- The property method must be ReadOnlyDoubleProperty
- The accessor type is from Method
--> In the displayed form the field is still editable and not disabled

**Comment by amischler** [comment]
Deployed in 8.0.8-SNAPSHOT

**Comment by amischler** [comment]
Fixed in 8.0.8
