### ISSUE TITLE
Render multiple beans of the same type

### ISSUE THREAD

**Issue by milanov** [dooApp/FXForm2#98]
Hi,

First of all kudos for the great project, keep up the good work.

I'm trying to render a form consisting of a variable number of Questions, where Question is a simple Java bean with label/value properties. A ListProperty does not do the job for me (since questions may have different types and therefore different form elements), so I tried instantiating FXForm with multiple instances of Question:

    form.setSource(new MultipleBeanSource(new Question(), new Question()));
Unfortunately I get a `You can't give two beans of the same type.` error.
Is there currently a way in which I can achieve that variability of questions?

**Comment by amischler** [comment]
The MultipleBeanSource is not intended to mix several bean of the same types, and the FXForm architecture won't allow to do this easily.
In your case I would recommend to create one form per Question.
For example you can put all your Question in a ListView and customize the cell factory to create an FXForm for each cell. Would it suit you needs?

**Comment by milanov** [comment]
Yes, that worked, thanks :+1:. I decided to implement the renderer myself, however, since it's a quite specific case.

**Comment by amischler** [comment]
Ok, great!
